using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Drawing;
using DocumentFormat.OpenXml.Drawing.Charts;
using DocumentFormat.OpenXml.Drawing.Spreadsheet;
using DocumentFormat.OpenXml.Spreadsheet;

using A = DocumentFormat.OpenXml.Drawing;
using C = DocumentFormat.OpenXml.Drawing.Charts;
using Xdr = DocumentFormat.OpenXml.Drawing.Spreadsheet;

namespace AdiPAIE_V02.Module.Services;

public enum ChartType
{
    Pie,
    ColumnBar,
    HorizontalBar,
    StackedBar
}

public class ChartDef
{
    public string Title { get; set; } = string.Empty;
    public ChartType Type { get; set; }
    public string CategoryRange { get; set; } = string.Empty;
    public string[] ValueRanges { get; set; } = Array.Empty<string>();
    public string[] SeriesNames { get; set; } = Array.Empty<string>();
    public string[] Colors { get; set; } = Array.Empty<string>();
    public int AnchorRow { get; set; }
    public int AnchorCol { get; set; }
    public int Width { get; set; } = 12;
    public int Height { get; set; } = 15;

    /// <summary>Labels des catégories (ex: "Hommes", "Femmes") pour peupler le cache du graphique.</summary>
    public string[]? CategoryLabels { get; set; }
    /// <summary>Valeurs numériques par série. SeriesValues[0] = valeurs de la 1ère série, etc.</summary>
    public double[][]? SeriesValues { get; set; }
}

/// <summary>
/// Injects native Excel charts into an existing workbook (typically generated by ClosedXML)
/// using the OpenXML SDK. This bridges the gap since ClosedXML does not support chart creation.
/// </summary>
public static class ExcelChartInjector
{
    private const long EmuPerPixel = 9525;
    private const long DefaultColumnWidthEmu = 64 * EmuPerPixel; // ~64px per column
    private const long DefaultRowHeightEmu = 20 * EmuPerPixel;   // ~20px per row

    /// <summary>
    /// Takes raw Excel bytes, injects the specified charts, and returns the modified workbook bytes.
    /// </summary>
    public static byte[] InjectCharts(byte[] workbookBytes, string targetSheetName, string dataSheetName, List<ChartDef> charts)
    {
        if (workbookBytes == null || charts == null || charts.Count == 0)
            return workbookBytes ?? Array.Empty<byte>();

        using var stream = new MemoryStream();
        stream.Write(workbookBytes, 0, workbookBytes.Length);
        stream.Position = 0;

        using (var document = SpreadsheetDocument.Open(stream, true))
        {
            var workbookPart = document.WorkbookPart
                ?? throw new InvalidOperationException("Workbook part not found.");

            var targetSheet = FindSheet(workbookPart, targetSheetName);
            var worksheetPart = (WorksheetPart)workbookPart.GetPartById(targetSheet.Id!.Value!);

            // Ensure the worksheet has a DrawingsPart
            var drawingsPart = worksheetPart.DrawingsPart;
            if (drawingsPart == null)
            {
                drawingsPart = worksheetPart.AddNewPart<DrawingsPart>();

                // Create WorksheetDrawing with required namespace declarations
                var wsDrawing = new Xdr.WorksheetDrawing();
                wsDrawing.AddNamespaceDeclaration("xdr",
                    "http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing");
                wsDrawing.AddNamespaceDeclaration("a",
                    "http://schemas.openxmlformats.org/drawingml/2006/main");
                drawingsPart.WorksheetDrawing = wsDrawing;

                // Insert <drawing r:id="..."/> in the correct schema position
                var drawingId = worksheetPart.GetIdOfPart(drawingsPart);
                var worksheet = worksheetPart.Worksheet;

                if (worksheet.GetFirstChild<DocumentFormat.OpenXml.Spreadsheet.Drawing>() == null)
                {
                    var drawingElem = new DocumentFormat.OpenXml.Spreadsheet.Drawing { Id = drawingId };
                    InsertDrawingInOrder(worksheet, drawingElem);
                }
            }

            var worksheetDrawing = drawingsPart.WorksheetDrawing;

            for (int i = 0; i < charts.Count; i++)
            {
                InjectSingleChart(drawingsPart, worksheetDrawing, charts[i], dataSheetName, (uint)i);
            }

            worksheetDrawing.Save(drawingsPart);
            document.Save();
        }

        return stream.ToArray();
    }

    /// <summary>
    /// Inserts the Drawing element in the correct schema position within the worksheet.
    /// Order: ... pageMargins, pageSetup, headerFooter, rowBreaks, colBreaks,
    ///        drawing, drawingHF, picture, oleObjects, controls, tableParts, extLst
    /// </summary>
    private static void InsertDrawingInOrder(DocumentFormat.OpenXml.Spreadsheet.Worksheet worksheet,
        DocumentFormat.OpenXml.Spreadsheet.Drawing drawingElem)
    {
        // Elements that must come AFTER <drawing> — we insert BEFORE the first one found
        var afterTypes = new[]
        {
            typeof(DocumentFormat.OpenXml.Spreadsheet.LegacyDrawing),
            typeof(DocumentFormat.OpenXml.Spreadsheet.LegacyDrawingHeaderFooter),
            typeof(DocumentFormat.OpenXml.Spreadsheet.Picture),
            typeof(DocumentFormat.OpenXml.Spreadsheet.OleObjects),
            typeof(DocumentFormat.OpenXml.Spreadsheet.Controls),
            typeof(DocumentFormat.OpenXml.Spreadsheet.TableParts),
            typeof(DocumentFormat.OpenXml.Spreadsheet.ExtensionList),
        };

        foreach (var type in afterTypes)
        {
            var existing = worksheet.ChildElements.FirstOrDefault(e => e.GetType() == type);
            if (existing != null)
            {
                worksheet.InsertBefore(drawingElem, existing);
                return;
            }
        }

        // No "after" elements found — safe to append
        worksheet.Append(drawingElem);
    }

    private static Sheet FindSheet(WorkbookPart workbookPart, string sheetName)
    {
        var sheets = workbookPart.Workbook.Sheets
            ?? throw new InvalidOperationException("No sheets found in workbook.");

        return sheets.Elements<Sheet>().FirstOrDefault(s => s.Name?.Value == sheetName)
            ?? throw new InvalidOperationException($"Sheet '{sheetName}' not found in workbook.");
    }

    private static void InjectSingleChart(
        DrawingsPart drawingsPart,
        Xdr.WorksheetDrawing worksheetDrawing,
        ChartDef chartDef,
        string dataSheetName,
        uint chartIndex)
    {
        // Create a ChartPart
        var chartPart = drawingsPart.AddNewPart<ChartPart>();
        string chartPartId = drawingsPart.GetIdOfPart(chartPart);

        // Build the chart
        var chartSpace = BuildChartSpace(chartDef, dataSheetName);
        chartPart.ChartSpace = chartSpace;

        // Create the TwoCellAnchor in the worksheet drawing
        var anchor = CreateTwoCellAnchor(chartDef, chartPartId, chartIndex);
        worksheetDrawing.Append(anchor);
    }

    private static C.ChartSpace BuildChartSpace(ChartDef chartDef, string dataSheetName)
    {
        var chart = new C.Chart();

        // Title
        if (!string.IsNullOrEmpty(chartDef.Title))
        {
            chart.Title = CreateChartTitle(chartDef.Title);
            chart.AutoTitleDeleted = new C.AutoTitleDeleted { Val = false };
        }

        // Plot area
        var plotArea = new C.PlotArea();
        plotArea.Append(new C.Layout());

        // Build the appropriate chart type
        switch (chartDef.Type)
        {
            case ChartType.Pie:
                plotArea.Append(BuildPieChart(chartDef, dataSheetName));
                break;
            case ChartType.ColumnBar:
                plotArea.Append(BuildBarChart(chartDef, dataSheetName, C.BarDirectionValues.Column, C.BarGroupingValues.Clustered));
                AppendAxes(plotArea);
                break;
            case ChartType.HorizontalBar:
                plotArea.Append(BuildBarChart(chartDef, dataSheetName, C.BarDirectionValues.Bar, C.BarGroupingValues.Clustered));
                AppendAxes(plotArea);
                break;
            case ChartType.StackedBar:
                plotArea.Append(BuildBarChart(chartDef, dataSheetName, C.BarDirectionValues.Bar, C.BarGroupingValues.PercentStacked));
                AppendAxes(plotArea);
                break;
        }

        chart.PlotArea = plotArea;

        // Legend (except for single-series pie charts)
        if (chartDef.Type != ChartType.Pie || chartDef.SeriesNames.Length > 1)
        {
            chart.Legend = new C.Legend(
                new C.LegendPosition { Val = C.LegendPositionValues.Bottom },
                new C.Overlay { Val = false }
            );
        }

        chart.PlotVisibleOnly = new C.PlotVisibleOnly { Val = true };
        chart.DisplayBlanksAs = new C.DisplayBlanksAs { Val = C.DisplayBlanksAsValues.Gap };

        var chartSpace = new C.ChartSpace();
        chartSpace.Append(new C.EditingLanguage { Val = "fr-FR" });
        chartSpace.Append(chart);

        // Print settings
        chartSpace.Append(new C.PrintSettings(
            new C.HeaderFooter(),
            new C.PageMargins
            {
                Bottom = 0.75D,
                Left = 0.7D,
                Right = 0.7D,
                Top = 0.75D,
                Header = 0.3D,
                Footer = 0.3D
            }
        ));

        return chartSpace;
    }

    private static C.Title CreateChartTitle(string titleText)
    {
        var run = new A.Run();
        run.Append(new A.RunProperties
        {
            Language = "fr-FR",
            FontSize = 1200,
            Bold = true
        });
        run.Append(new A.Text(titleText));

        var paragraph = new A.Paragraph();
        paragraph.Append(new A.ParagraphProperties(
            new A.DefaultRunProperties
            {
                Language = "fr-FR",
                FontSize = 1200,
                Bold = true
            }
        ));
        paragraph.Append(run);

        var richText = new C.ChartText(
            new C.RichText(
                new A.BodyProperties(),
                new A.ListStyle(),
                paragraph
            )
        );

        return new C.Title(
            richText,
            new C.Overlay { Val = false }
        );
    }

    #region Pie Chart

    private static C.PieChart BuildPieChart(ChartDef chartDef, string dataSheetName)
    {
        var pieChart = new C.PieChart();
        pieChart.Append(new C.VaryColors { Val = true });

        string valueRange = chartDef.ValueRanges.Length > 0 ? chartDef.ValueRanges[0] : "B2:B3";
        string seriesName = chartDef.SeriesNames.Length > 0 ? chartDef.SeriesNames[0] : "Series1";

        var series = new C.PieChartSeries();
        series.Append(new C.Index { Val = 0u });
        series.Append(new C.Order { Val = 0u });
        series.Append(CreateSeriesText(seriesName));

        // Apply colors to individual data points for pie charts
        if (chartDef.Colors.Length > 0)
        {
            int pointCount = chartDef.CategoryLabels?.Length ?? EstimatePointCount(chartDef.CategoryRange);
            for (uint pt = 0; pt < Math.Min(pointCount, chartDef.Colors.Length); pt++)
            {
                series.Append(CreateDataPoint(pt, chartDef.Colors[pt]));
            }
        }

        // Category axis reference (avec cache pré-rempli)
        series.Append(CreateCategoryAxisData(dataSheetName, chartDef.CategoryRange, chartDef.CategoryLabels));

        // Value axis reference (avec cache pré-rempli)
        double[]? vals = chartDef.SeriesValues?.Length > 0 ? chartDef.SeriesValues[0] : null;
        series.Append(CreateValues(dataSheetName, valueRange, vals));

        pieChart.Append(series);

        // Data labels: show percentage and category name
        var dataLabels = new C.DataLabels(
            new C.ShowLegendKey { Val = false },
            new C.ShowValue { Val = false },
            new C.ShowCategoryName { Val = true },
            new C.ShowSeriesName { Val = false },
            new C.ShowPercent { Val = true },
            new C.ShowBubbleSize { Val = false },
            new C.Separator { Text = "\n" }
        );
        pieChart.Append(dataLabels);

        return pieChart;
    }

    private static C.DataPoint CreateDataPoint(uint index, string hexColor)
    {
        var solidFill = new A.SolidFill(
            new A.RgbColorModelHex { Val = hexColor }
        );

        var shapeProperties = new C.ChartShapeProperties(solidFill);

        return new C.DataPoint(
            new C.Index { Val = index },
            new C.Bubble3D { Val = false },
            shapeProperties
        );
    }

    #endregion

    #region Bar/Column Chart

    private static C.BarChart BuildBarChart(
        ChartDef chartDef,
        string dataSheetName,
        C.BarDirectionValues direction,
        C.BarGroupingValues grouping)
    {
        var barChart = new C.BarChart();
        barChart.Append(new C.BarDirection { Val = direction });
        barChart.Append(new C.BarGrouping { Val = grouping });
        barChart.Append(new C.VaryColors { Val = false });

        for (int i = 0; i < chartDef.ValueRanges.Length; i++)
        {
            var series = new C.BarChartSeries();
            series.Append(new C.Index { Val = (uint)i });
            series.Append(new C.Order { Val = (uint)i });

            string seriesName = i < chartDef.SeriesNames.Length
                ? chartDef.SeriesNames[i]
                : $"Series{i + 1}";
            series.Append(CreateSeriesText(seriesName));

            // Apply color to entire series
            if (i < chartDef.Colors.Length)
            {
                var solidFill = new A.SolidFill(
                    new A.RgbColorModelHex { Val = chartDef.Colors[i] }
                );
                series.Append(new C.ChartShapeProperties(solidFill));
            }

            // Category axis reference (avec cache pré-rempli)
            series.Append(CreateCategoryAxisData(dataSheetName, chartDef.CategoryRange, chartDef.CategoryLabels));

            // Value axis reference (avec cache pré-rempli)
            double[]? vals = chartDef.SeriesValues != null && i < chartDef.SeriesValues.Length
                ? chartDef.SeriesValues[i] : null;
            series.Append(CreateValues(dataSheetName, chartDef.ValueRanges[i], vals));

            barChart.Append(series);
        }

        // Data labels: show values
        var dataLabels = new C.DataLabels(
            new C.ShowLegendKey { Val = false },
            new C.ShowValue { Val = true },
            new C.ShowCategoryName { Val = false },
            new C.ShowSeriesName { Val = false },
            new C.ShowPercent { Val = false },
            new C.ShowBubbleSize { Val = false }
        );
        barChart.Append(dataLabels);

        // Axis IDs (category and value axes)
        barChart.Append(new C.AxisId { Val = 1u });
        barChart.Append(new C.AxisId { Val = 2u });

        return barChart;
    }

    #endregion

    #region Chart Axes

    /// <summary>
    /// Ajoute les axes Catégorie et Valeur au PlotArea (obligatoire pour les bar/column charts).
    /// </summary>
    private static void AppendAxes(C.PlotArea plotArea)
    {
        // Axe des catégories (ID=1, croise ID=2)
        var catAxis = new C.CategoryAxis(
            new C.AxisId { Val = 1u },
            new C.Scaling(new C.Orientation { Val = C.OrientationValues.MinMax }),
            new C.Delete { Val = false },
            new C.AxisPosition { Val = C.AxisPositionValues.Bottom },
            new C.TickLabelPosition { Val = C.TickLabelPositionValues.NextTo },
            new C.CrossingAxis { Val = 2u },
            new C.Crosses { Val = C.CrossesValues.AutoZero },
            new C.AutoLabeled { Val = true },
            new C.LabelAlignment { Val = C.LabelAlignmentValues.Center },
            new C.LabelOffset { Val = 100 }
        );
        plotArea.Append(catAxis);

        // Axe des valeurs (ID=2, croise ID=1)
        var valAxis = new C.ValueAxis(
            new C.AxisId { Val = 2u },
            new C.Scaling(new C.Orientation { Val = C.OrientationValues.MinMax }),
            new C.Delete { Val = false },
            new C.AxisPosition { Val = C.AxisPositionValues.Left },
            new C.NumberingFormat { FormatCode = "General", SourceLinked = true },
            new C.TickLabelPosition { Val = C.TickLabelPositionValues.NextTo },
            new C.CrossingAxis { Val = 1u },
            new C.Crosses { Val = C.CrossesValues.AutoZero },
            new C.CrossBetween { Val = C.CrossBetweenValues.Between }
        );
        plotArea.Append(valAxis);
    }

    #endregion

    #region Axis References

    private static C.SeriesText CreateSeriesText(string name)
    {
        return new C.SeriesText(
            new C.NumericValue(name)
        );
    }

    private static C.CategoryAxisData CreateCategoryAxisData(string sheetName, string range, string[]? labels = null)
    {
        string formula = $"'{sheetName}'!${ConvertToAbsoluteRange(range)}";
        int count = labels?.Length ?? EstimatePointCount(range);

        var stringReference = new C.StringReference();
        stringReference.Append(new C.Formula(formula));

        var stringCache = new C.StringCache();
        stringCache.Append(new C.PointCount { Val = (uint)count });

        // Peupler le cache avec les libellés réels
        if (labels != null)
        {
            for (uint i = 0; i < labels.Length; i++)
            {
                stringCache.Append(new C.StringPoint(new C.NumericValue(labels[i])) { Index = i });
            }
        }

        stringReference.Append(stringCache);
        return new C.CategoryAxisData(stringReference);
    }

    private static C.Values CreateValues(string sheetName, string range, double[]? values = null)
    {
        string formula = $"'{sheetName}'!${ConvertToAbsoluteRange(range)}";
        int count = values?.Length ?? EstimatePointCount(range);

        var numberReference = new C.NumberReference();
        numberReference.Append(new C.Formula(formula));

        var numberingCache = new C.NumberingCache();
        numberingCache.Append(new C.FormatCode("General"));
        numberingCache.Append(new C.PointCount { Val = (uint)count });

        // Peupler le cache avec les valeurs réelles
        if (values != null)
        {
            for (uint i = 0; i < values.Length; i++)
            {
                numberingCache.Append(new C.NumericPoint(new C.NumericValue(values[i].ToString(System.Globalization.CultureInfo.InvariantCulture))) { Index = i });
            }
        }

        numberReference.Append(numberingCache);
        return new C.Values(numberReference);
    }

    #endregion

    #region TwoCellAnchor

    private static Xdr.TwoCellAnchor CreateTwoCellAnchor(ChartDef chartDef, string chartPartId, uint chartIndex)
    {
        var fromMarker = new Xdr.FromMarker(
            new Xdr.ColumnId(chartDef.AnchorCol.ToString()),
            new Xdr.ColumnOffset("0"),
            new Xdr.RowId(chartDef.AnchorRow.ToString()),
            new Xdr.RowOffset("0")
        );

        var toMarker = new Xdr.ToMarker(
            new Xdr.ColumnId((chartDef.AnchorCol + chartDef.Width).ToString()),
            new Xdr.ColumnOffset("0"),
            new Xdr.RowId((chartDef.AnchorRow + chartDef.Height).ToString()),
            new Xdr.RowOffset("0")
        );

        var graphicFrame = CreateGraphicFrame(chartPartId, chartIndex);

        var anchor = new Xdr.TwoCellAnchor(
            fromMarker,
            toMarker,
            graphicFrame,
            new Xdr.ClientData()
        );

        return anchor;
    }

    private static Xdr.GraphicFrame CreateGraphicFrame(string chartPartId, uint chartIndex)
    {
        var graphicFrame = new Xdr.GraphicFrame();

        // Non-visual properties
        var nvProps = new Xdr.NonVisualGraphicFrameProperties(
            new Xdr.NonVisualDrawingProperties
            {
                Id = chartIndex + 2u, // start from 2 to avoid conflict with other drawing objects
                Name = $"Chart {chartIndex + 1}"
            },
            new Xdr.NonVisualGraphicFrameDrawingProperties()
        );
        graphicFrame.Append(nvProps);

        // Transform
        graphicFrame.Append(new Xdr.Transform(
            new A.Offset { X = 0, Y = 0 },
            new A.Extents { Cx = 0, Cy = 0 }
        ));

        // Graphic with chart reference
        var chartRef = new C.ChartReference { Id = chartPartId };

        var graphicData = new A.GraphicData(chartRef)
        {
            Uri = "http://schemas.openxmlformats.org/drawingml/2006/chart"
        };

        graphicFrame.Append(new A.Graphic(graphicData));

        return graphicFrame;
    }

    #endregion

    #region Range Helpers

    /// <summary>
    /// Converts a range like "A2:A3" to "$A$2:$A$3" for use in chart formulas.
    /// If the range already contains '$', it is returned as-is.
    /// </summary>
    private static string ConvertToAbsoluteRange(string range)
    {
        if (range.Contains('$'))
            return range;

        var parts = range.Split(':');
        if (parts.Length == 2)
        {
            return $"{MakeAbsoluteCell(parts[0])}:{MakeAbsoluteCell(parts[1])}";
        }
        return MakeAbsoluteCell(range);
    }

    private static string MakeAbsoluteCell(string cell)
    {
        cell = cell.Trim();
        int splitIndex = 0;
        for (int i = 0; i < cell.Length; i++)
        {
            if (char.IsDigit(cell[i]))
            {
                splitIndex = i;
                break;
            }
        }

        if (splitIndex == 0)
            return cell;

        string col = cell[..splitIndex];
        string row = cell[splitIndex..];
        return $"${col}${row}";
    }

    /// <summary>
    /// Estimates the number of data points from a range string like "A2:A5" => 4.
    /// </summary>
    private static int EstimatePointCount(string range)
    {
        try
        {
            var parts = range.Replace("$", "").Split(':');
            if (parts.Length != 2)
                return 1;

            int startRow = ExtractRowNumber(parts[0]);
            int endRow = ExtractRowNumber(parts[1]);

            string startCol = ExtractColumnLetters(parts[0]);
            string endCol = ExtractColumnLetters(parts[1]);

            if (startCol == endCol)
            {
                // Single column range: count = endRow - startRow + 1
                return Math.Max(1, endRow - startRow + 1);
            }
            else if (startRow == endRow)
            {
                // Single row range: count by columns
                int startColNum = ColumnLetterToNumber(startCol);
                int endColNum = ColumnLetterToNumber(endCol);
                return Math.Max(1, endColNum - startColNum + 1);
            }

            return Math.Max(1, endRow - startRow + 1);
        }
        catch
        {
            return 2; // safe fallback
        }
    }

    private static int ExtractRowNumber(string cellRef)
    {
        var digits = new string(cellRef.Where(char.IsDigit).ToArray());
        return int.TryParse(digits, out int row) ? row : 1;
    }

    private static string ExtractColumnLetters(string cellRef)
    {
        return new string(cellRef.Where(char.IsLetter).ToArray());
    }

    private static int ColumnLetterToNumber(string col)
    {
        int result = 0;
        foreach (char c in col.ToUpperInvariant())
        {
            result = result * 26 + (c - 'A' + 1);
        }
        return result;
    }

    #endregion
}
