<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Model.DesignedDiffs.xafml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Model.DesignedDiffs.xafml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.ExpressApp" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.AuditTrail.Xpo" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Chart" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.CloneObject" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.ConditionalAppearance" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Dashboards" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Kpi" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.MultiTenancy.Xpo" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Notifications" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Objects" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Office" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.PivotChart" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.PivotGrid" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.ReportsV2" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Scheduler" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.ScriptRecorder" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Security" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Security.Xpo" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.StateMachine" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.TreeListEditors" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Validation" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.ViewVariantsModule" Version="25.1.*" />
    <PackageReference Include="DevExpress.ExpressApp.Win" Version="25.1.5" />
    <PackageReference Include="DevExpress.ExpressApp.Xpo" Version="25.1.*" />
    <PackageReference Include="DevExpress.Persistent.Base" Version="25.1.*" />
    <PackageReference Include="DevExpress.Persistent.BaseImpl.Xpo" Version="25.1.*" />
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.Graph" Version="5.93.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
    
  </ItemGroup>
  <ItemGroup>
    <None Update="UnusableNodes.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes1.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes10.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes11.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes12.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes13.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes14.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes15.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes16.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes17.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes18.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes19.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes2.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes20.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes21.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes22.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes23.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes24.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes3.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes4.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes5.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes6.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes7.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes8.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
    <None Update="UnusableNodes9.xml">
      <DependentUpon>Model.DesignedDiffs.xafml</DependentUpon>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Reports\NewFolder\" />
  </ItemGroup>
</Project>
